### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by jittaearn** [plumest/django-polls#1]
- Cannot Migrate 
```
>>> python3 manage.py migrate
Traceback (most recent call last):
    ...
ModuleNotFoundError: No module named 'dj_database_url'
```
- Bad Request 400   
<img width="1440" alt="Screen Shot 2562-09-25 at 12 52 44" src="https://user-images.githubusercontent.com/42648115/65572805-6a698e80-df93-11e9-9d79-ecb0e4829d66.png">

**Comment by plumest** [comment]
@jittaearn 
- The first problem you should install dj_database_url first. ( If you follow the requirement, it should already installed. )
- The second problem I fix it already. Please check it again. Then comment me on the pull request.

**Comment by plumest** [comment]
I press wrong button LOL.

**Comment by jittaearn** [comment]
Everything works perfectly now

**Comment by jittaearn** [comment]
@plumest 

Everything seems to work perfectly fine. I was able to run the server. Nicely done!
